microservice.contextPath: '/user'
server:
  port: 8080
info:
  component: User Service

spring:
  application:
     name: user-service
  mvc:
    dispatch-trace-request: true
  data:
    cassandra:
      contact-points: localhost
      port          : 9042
      keyspace-name : samplekeyspace
      username      :
      password      :
      ssl           : false

logging:
  level:
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: C:/Users/Dhananjay/Desktop/application.log